"""Add severity column to Accident model

Revision ID: 4da39a61ece0
Revises: 77102e4be31d
Create Date: 2025-03-13 20:32:46.554558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da39a61ece0'
down_revision = '77102e4be31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident', schema=None) as batch_op:
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
