"""Fix beneficiary model

Revision ID: 77102e4be31d
Revises: 
Create Date: 2025-03-13 00:19:41.302726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77102e4be31d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('policy_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'policy', ['policy_id'], ['id'])
        batch_op.drop_column('relation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('policy_id')
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
